export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Login } from "./Login";
export { default as NewsFeed } from "./NewsFeed";
export { default as Register } from "./Register";
export { default as Messages } from "./Messages";
export { default as Comments } from "./Comments";
export { default as NewComment } from "./NewComment";
export { default as FullpageFriendsLists } from "./FullpageFriendsLists";
